### ISSUE TITLE
Re: 'About'

### ISSUE THREAD

**Issue by MancRickster** [ministryofjustice/hmpps-probation-integration-services#4200]
Problem with 'About' (https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/projects/make-recall-decisions-and-delius/)

Hey there, I think this page is missing the 'prison-recall.recommendation.deleted' event, as is https://github.com/ministryofjustice/hmpps-probation-integration-services/blob/main/projects/make-recall-decisions-and-delius/README.md - let me know if you want me to do anything?

cheers,
Rick

**Comment by marcus-bcl** [comment]
Thanks Rick, well spotted.  It appears we also have the 'prison-recall.recommendation.started' event in there, which is no longer used.

The auto-generated [AsyncAPI docs](https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/projects/make-recall-decisions-and-delius/asyncapi-reference.html) is correct, but the messages haven't been manually updated in the README yet.  Once the README is updated, it will also update the 'About' section in the docs.

Feel free to send a PR to get that updated if you like, or I can add a ticket to our backlog to do it if not?
